package model

type Account struct {
	Id       int64  `json:"id"`
	UserId   string `json:"userId"`
	Password string `json:"password"`
	IsUsed   int    `json:"isUsed"`
}

type UserLogin struct {
	UserId    string `json:"userId" binding:"required" validate:"required,gte=5,lte=20"`
	Password  string `json:"password" binding:"required" validate:"required,gte=8,lte=30"`
	PushToken string `json:"pushToken"`
}

type NewAccountForm struct {
	Id              int64  `json:"id"` // Id is not a input value. It is generated by server
	UserId          string `json:"userId" binding:"required" validate:"required,gte=6,lte=20"`
	Password        string `json:"password" binding:"required" validate:"required,gte=8,lte=30"`
	ConfirmPassword string `json:"confirmPassword" binding:"required" validate:"required,gte=8,lte=30"`
}
